# url: https://127.0.0.1
# baseurl: ""

url: http://ccop.crest-centre.net
baseurl: ""

# Site settings
title: CCOP
email: your-email@domain.com
description: "Cyber Common Operating Picture Project Home Page"


# Team names, titles and social links
people:
- name: Prof. M. Ali Babar
  pic: ali
  position: Project Lead
  social:
    - title: twitter
      url: https://twitter.com/alibabar

- name: Dr. Mansooreh Zahedi
  pic: mansooreh
  position: Researcher - Socio-Technical
  social:
    - title: twitter
      url: https://twitter.com/MansoorehZ

- name: Dr. Asangi Jayatilaka
  pic: asangi
  position: Researcher - Socio-Technical
  social:
    - title: twitter
      url: https://twitter.com/DrAsangiJ

- name: Dr. Nguyen Khoi Tran
  pic: nguyen
  position: Researcher - Architecture
  social:
    - title: twitter
      url: https://twitter.com/GenTran91

- name: Liuyue (William) Jiang
  pic: liuyue
  position: PhD. Student - Lead Engineer
  social:
    - title: twitter
      url: https://twitter.com/williamjiangau

- name: Anupam . 
  pic: avatar-placeholder
  position: Research Engineer
  social:
    - title: twitter
      url: https://twitter.com/williamjiangau

- name: Aditya Pujara
  pic: aditya
  position: Summer Research Scholarship Student
  social:
    - title: twitter
      url: https://twitter.com/

- name: Kieren Funk
  pic: avatar-placeholder
  position: Summer Research Scholarship Student
  social:
    - title: twitter
      url: https://twitter.com/

- name: Shayla Nguyen
  pic: avatar-placeholder
  position: Summer Research Scholarship Student
  social:
    - title: twitter
      url: https://twitter.com/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/crest_uofa

# Postal address (add as many lines as necessary)
address:
  - line: The University of Adelaide
  - line: Ingkarni Wardli
  - line: Adelaide SA 5005

# Build settings
markdown: kramdown
permalink: pretty